# Flags for data set and data dirs
dataset: '20230422'
basdir: 'D:/dataset/PressureDataset'
sub_ids: 'S01'
seq_name: 'MoCap_20230422_094530'
output_dir: 'output'
color_size:
  - 1280
  - 720
depth_size:
  - 640
  - 576


init_idx_start: 1
init_idx_end: 40

num_shape_comps: 10
model_gender: 'male'

shape_weights: 0.01
depth_weights: 80.0
keypoint_weights: 0.01
penetrate_weights: 15.0
contact_weights: 0
maxiters: 101

