# Flags for data set and data dirs
dataset: '20230422'
basdir: '/data/PressureDataset'
sub_ids: 'S01'
label_output_dir: '/data/yuanhaolei/PressureDataset_label'
seq_name: 'MoCap_20230422_092117'
output_dir: 'output'
color_size:
  - 1280
  - 720
depth_size:
  - 640
  - 576

frame_range:
  - 0
  - 167

num_shape_comps: 10
model_gender: 'male'

init_idx_start: 0
init_idx_end: 167
shape_weights: 0.01
depth_weights: 60.0
keypoint_weights: 0.01
penetrate_weights: 15.0
contact_weights: 0
maxiters: 101
