# Flags for data set and data dirs
dataset: 'PressureDataset'
basdir: 'E:/dataset'
sub_ids: 'S12'
seq_name: 'MoCap_20230422_145333'
output_dir: 'output'
color_size:
  - 1280
  - 720
depth_size:
  - 640
  - 576

frame_range:
  - 24
  - 145

num_shape_comps: 10
model_gender: 'male'

init_model: True
shape_weights: 0.01
depth_weights: 10.0
keypoint_weights: 0.0001
penetrate_weights: 10.0
contact_weights: 0
maxiters: 101
