defaults:
    - _self_
    # - method: optimize_trans
    - task: tiaosheng
    # - override hydra/job_logging: custom

# hydra parameters
hydra:
    # sets level of all command line loggers to 'DEBUG'
    verbose: False
    job:
        chdir: False

# wandb parameters
# wandb:
#     project: 'template-test'
    
# general parameters for all experiments
gpu: 0
# scene_rgbd: 'models/template_scene_rgbd.npy'
# smpl_file: 'models/SMPL_female.pkl'
# mask_path: 'models/insole_mask'
seed: null